# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Ask you question')),
                ('description', redactor.fields.RedactorField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
