# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20161030_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='InapproptiateWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60)),
            ],
        ),
    ]
