# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_surveyoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='surveyoffer',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 11, 11, 13, 16, 16, 770314, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
