# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20161111_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyoffer',
            name='date',
            field=models.TimeField(),
        ),
    ]
