# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20161111_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyoffer',
            old_name='date',
            new_name='time',
        ),
    ]
