# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20161111_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoffer',
            name='time',
        ),
    ]
