# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20161116_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyoffer',
            old_name='id',
            new_name='survey_id',
        ),
    ]
