# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_surveyoffer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFromOnePreson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=70)),
                ('avg_vote', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='surveyoffer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
