# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20161205_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackfromonepreson',
            name='survey_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
